<?php

namespace Database\Seeders;

use App\Models\List_Transaction_Laundry;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Log;

class ListTransactionsLaundrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        try {
            List_Transaction_Laundry::insert([
                [
                    'id_transaction_laundry' => 1,
                    'id_item_laundry' => 1,
                    'price_list_transaction_laundry' => 12000,
                    'weight_list_transaction_laundry' => 2.5,
                    'total_price_list_transaction_laundry' => 30000,
                    'status_list_transaction_laundry' => 'completed',
                    'note_list_transaction_laundry' => 'Bersihkan noda di bagian lengan',
                    'is_active_list_transaction_laundry' => 'active',
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id_transaction_laundry' => 1,
                    'id_item_laundry' => 2,
                    'price_list_transaction_laundry' => 15000,
                    'weight_list_transaction_laundry' => 3.0,
                    'total_price_list_transaction_laundry' => 20000,
                    'status_list_transaction_laundry' => 'pending',
                    'note_list_transaction_laundry' => 'Pakai pewangi ekstra',
                    'is_active_list_transaction_laundry' => 'active',
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id_transaction_laundry' => 2,
                    'id_item_laundry' => 3,
                    'price_list_transaction_laundry' => 18000,
                    'weight_list_transaction_laundry' => 4.2,
                    'total_price_list_transaction_laundry' => 40000,
                    'status_list_transaction_laundry' => 'completed',
                    'note_list_transaction_laundry' => 'Cuci dengan suhu rendah',
                    'is_active_list_transaction_laundry' => 'active',
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id_transaction_laundry' => 2,
                    'id_item_laundry' => 4,
                    'price_list_transaction_laundry' => 9000,
                    'weight_list_transaction_laundry' => 1.5,
                    'total_price_list_transaction_laundry' => 10000,
                    'status_list_transaction_laundry' => 'cancelled',
                    'note_list_transaction_laundry' => 'Dibatalkan oleh pelanggan',
                    'is_active_list_transaction_laundry' => 'active',
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id_transaction_laundry' => 3,
                    'id_item_laundry' => 5,
                    'price_list_transaction_laundry' => 25000,
                    'weight_list_transaction_laundry' => 5.0,
                    'total_price_list_transaction_laundry' => 50000,
                    'status_list_transaction_laundry' => 'pending',
                    'note_list_transaction_laundry' => 'Gunakan deterjen hypoallergenic',
                    'is_active_list_transaction_laundry' => 'active',
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id_transaction_laundry' => 3,
                    'id_item_laundry' => 6,
                    'price_list_transaction_laundry' => 12000,
                    'weight_list_transaction_laundry' => 2.0,
                    'total_price_list_transaction_laundry' => 20000,
                    'status_list_transaction_laundry' => 'completed',
                    'note_list_transaction_laundry' => 'Jemur dengan cara alami',
                    'is_active_list_transaction_laundry' => 'active',
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id_transaction_laundry' => 4,
                    'id_item_laundry' => 7,
                    'price_list_transaction_laundry' => 13500,
                    'weight_list_transaction_laundry' => 2.3,
                    'total_price_list_transaction_laundry' => 20000,
                    'status_list_transaction_laundry' => 'completed',
                    'note_list_transaction_laundry' => 'Keringkan dengan mesin',
                    'is_active_list_transaction_laundry' => 'active',
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id_transaction_laundry' => 4,
                    'id_item_laundry' => 8,
                    'price_list_transaction_laundry' => 16000,
                    'weight_list_transaction_laundry' => 3.5,
                    'total_price_list_transaction_laundry' => 30000,
                    'status_list_transaction_laundry' => 'pending',
                    'note_list_transaction_laundry' => 'Gunakan pelembut kain',
                    'is_active_list_transaction_laundry' => 'active',
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id_transaction_laundry' => 5,
                    'id_item_laundry' => 9,
                    'price_list_transaction_laundry' => 11000,
                    'weight_list_transaction_laundry' => 1.8,
                    'total_price_list_transaction_laundry' => 10000,
                    'status_list_transaction_laundry' => 'cancelled',
                    'note_list_transaction_laundry' => 'Pelanggan membatalkan pesanan',
                    'is_active_list_transaction_laundry' => 'active',
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id_transaction_laundry' => 5,
                    'id_item_laundry' => 10,
                    'price_list_transaction_laundry' => 20000,
                    'weight_list_transaction_laundry' => 4.0,
                    'total_price_list_transaction_laundry' => 40000,
                    'status_list_transaction_laundry' => 'completed',
                    'note_list_transaction_laundry' => 'Pastikan tidak ada noda tersisa',
                    'is_active_list_transaction_laundry' => 'active',
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id_transaction_laundry' => 1,
                    'id_item_laundry' => 1,
                    'price_list_transaction_laundry' => 14000,
                    'weight_list_transaction_laundry' => 2.6,
                    'total_price_list_transaction_laundry' => 30000,
                    'status_list_transaction_laundry' => 'pending',
                    'note_list_transaction_laundry' => 'Cuci dengan air hangat',
                    'is_active_list_transaction_laundry' => 'active',
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id_transaction_laundry' => 1,
                    'id_item_laundry' => 2,
                    'price_list_transaction_laundry' => 12500,
                    'weight_list_transaction_laundry' => 2.1,
                    'total_price_list_transaction_laundry' => 20000,
                    'status_list_transaction_laundry' => 'completed',
                    'note_list_transaction_laundry' => 'Keringkan dengan suhu rendah',
                    'is_active_list_transaction_laundry' => 'active',
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id_transaction_laundry' => 2,
                    'id_item_laundry' => 3,
                    'price_list_transaction_laundry' => 17500,
                    'weight_list_transaction_laundry' => 3.8,
                    'total_price_list_transaction_laundry' => 40000,
                    'status_list_transaction_laundry' => 'pending',
                    'note_list_transaction_laundry' => 'Gunakan deterjen organik',
                    'is_active_list_transaction_laundry' => 'active',
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id_transaction_laundry' => 2,
                    'id_item_laundry' => 4,
                    'price_list_transaction_laundry' => 10000,
                    'weight_list_transaction_laundry' => 1.7,
                    'total_price_list_transaction_laundry' => 20000,
                    'status_list_transaction_laundry' => 'completed',
                    'note_list_transaction_laundry' => 'Gunakan sikat untuk noda membandel',
                    'is_active_list_transaction_laundry' => 'active',
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id_transaction_laundry' => 3,
                    'id_item_laundry' => 5,
                    'price_list_transaction_laundry' => 23000,
                    'weight_list_transaction_laundry' => 4.8,
                    'total_price_list_transaction_laundry' => 50000,
                    'status_list_transaction_laundry' => 'pending',
                    'note_list_transaction_laundry' => 'Gunakan pelembut khusus',
                    'is_active_list_transaction_laundry' => 'active',
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id_transaction_laundry' => 3,
                    'id_item_laundry' => 6,
                    'price_list_transaction_laundry' => 15000,
                    'weight_list_transaction_laundry' => 3.2,
                    'total_price_list_transaction_laundry' => 30000,
                    'status_list_transaction_laundry' => 'completed',
                    'note_list_transaction_laundry' => 'Jangan pakai pemutih',
                    'is_active_list_transaction_laundry' => 'active',
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id_transaction_laundry' => 4,
                    'id_item_laundry' => 7,
                    'price_list_transaction_laundry' => 14500,
                    'weight_list_transaction_laundry' => 2.4,
                    'total_price_list_transaction_laundry' => 30000,
                    'status_list_transaction_laundry' => 'pending',
                    'note_list_transaction_laundry' => 'Tambahkan pewangi',
                    'is_active_list_transaction_laundry' => 'active',
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id_transaction_laundry' => 4,
                    'id_item_laundry' => 8,
                    'price_list_transaction_laundry' => 15500,
                    'weight_list_transaction_laundry' => 3.3,
                    'total_price_list_transaction_laundry' => 20000,
                    'status_list_transaction_laundry' => 'completed',
                    'note_list_transaction_laundry' => 'Gunakan setrika uap',
                    'is_active_list_transaction_laundry' => 'active',
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'id_transaction_laundry' => 5,
                    'id_item_laundry' => 9,
                    'price_list_transaction_laundry' => 21000,
                    'weight_list_transaction_laundry' => 4.5,
                    'total_price_list_transaction_laundry' => 50000,
                    'status_list_transaction_laundry' => 'pending',
                    'note_list_transaction_laundry' => 'Gunakan air dingin',
                    'is_active_list_transaction_laundry' => 'active',
                    'deleted_at' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
            ]);

            Log::info('Data list transaksi laundry berhasil disimpan');
        } catch (\Exception $error) {
            Log::error('Gagal menyimpan data list transaksi laundry: ' . $error->getMessage());
        }
    }
}
